# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RibsDog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RibsDog
  pod 'RIBs'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod "RxCoreData"
  pod 'SwiftLint'
  pod 'SwiftMessages'
  pod 'Hero'
  pod 'lottie-ios'
  pod 'NVActivityIndicatorView'
  pod 'SnapKit'

  target 'RibsDogTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  target 'RibsDogUITests' do
    # Pods for testing
  end

end
